spring.application.name=GalaxyBck

##DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

#JWT Config
jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}



# Google Maps
google.maps.api-key=${GOOGLE_MAPS_API_KEY}
google.maps.distance-matrix-url=${GOOGLE_MAPS_DISTANCE_MATRIX_URL}



