spring.application.name=GalaxyBck

# DataSource

spring.datasource.url=${SPRING_DATASOURCE_URL}
spring.datasource.username=${PGUSER}
spring.datasource.password=${PGPASSWORD}
spring.datasource.driver-class-name=org.postgresql.Driver

##DEV
#spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
#spring.datasource.username=postgres
#spring.datasource.password=admin
#spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=create-drop
spring.jpa.show-sql=false

# JWT
jwt.secret=94ebc258-1e51-4e6e-ac4e-08b217870bf1
jwt.expiration=86400000


# Google Maps
google.maps.api-key=AIzaSyDlDPvEKc0AmmYhgdN9BwaD9lZJZvLAnM4
google.maps.distance-matrix-url=https://maps.googleapis.com/maps/api/distancematrix/json
