spring.application.name=GalaxyBck

# DataSource

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver

#spring.datasource.url=${SPRING_DATASOURCE_URL}
#spring.datasource.username=${SPRING_DATASOURCE_USERNAME}
#spring.datasource.password=${SPRING_DATASOURCE_PASSWORD}
#spring.datasource.driver-class-name=org.postgresql.Driver


##DEV
spring.datasource.url=jdbc:postgresql://localhost:5432/postgres
spring.datasource.username=postgres
spring.datasource.password=admin
spring.datasource.driver-class-name=org.postgresql.Driver

# SQL Init
spring.sql.init.mode=always
spring.jpa.defer-datasource-initialization=true

# JPA / Hibernate
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=false

# JWT
#jwt.secret=${JWT_SECRET}
#jwt.expiration=86400000

jwt.secret=94ebc258-1e51-4e6e-ac4e-08b217870bf1
jwt.expiration=86400000



# Google Maps
#google.maps.api-key=${GOOGLE_MAPS_API_KEY}
google.maps.api-key=AIzaSyDlDPvEKc0AmmYhgdN9BwaD9lZJZvLAnM4
#google.maps.distance-matrix-url=${GOOGLE_MAPS_DISTANCE_MATRIX_URL}
google.maps.distance-matrix-url=https://maps.googleapis.com/maps/api/distancematrix/json



